@startuml Path

class Path{
    String path
    
    constructor(stringPath)
    static fromString(stringPath)
    
    isAbsolute()
    isRelative()
    isDirectory()
    isFile()

    directory()
    file()
    extension()

    join(aPathOrString)
    parse()
    relativeTo()
    
    asString()
}
@enduml