@startuml Point
class Point {
    Number x
    Number y

    constructor(x, y)
    fromArray([x, y])
    with(x, y)

    isEqual(aPoint)
    isZero()

    add(aNumber)
    addPoint(aPoint)
    sub(aNumber)
    subPoint(aPoint)
    translate(aNumber, aNumber)
    translateX(aNumber)
    translateY(aNumber)
    multiply(aNumber)
    multiplyPoint(aPoint)
    distance(aPoint)
    transposed()
    negated()
}
@enduml